# Generated by Django 2.1.3 on 2018-11-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='round',
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('M', 'Multiple Choice'), ('T', 'True or False'), ('S', 'Survey')], default='M', max_length=1),
        ),
    ]
