# Generated by Django 2.1.3 on 2018-11-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20181119_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='data',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='view',
            field=models.CharField(default='main', max_length=30),
        ),
    ]
