# Generated by Django 2.1.3 on 2018-11-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20181119_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='title',
            field=models.CharField(default='SJDV', max_length=30),
        ),
    ]
