# Generated by Django 2.1.3 on 2018-11-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_game_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('M', 'Multiple Choice'), ('T', 'True or False'), ('S', 'Survey'), ('R', 'Survey Rush')], default='M', max_length=1),
        ),
    ]
