# Generated by Django 2.1.3 on 2018-11-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20181120_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='play',
            field=models.BooleanField(default=False),
        ),
    ]
