# Generated by Django 2.1.3 on 2018-11-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_game_play'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='view',
            new_name='play_view',
        ),
        migrations.RemoveField(
            model_name='game',
            name='data',
        ),
        migrations.AddField(
            model_name='game',
            name='play_choice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='play_question',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='play_refresh',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='play_time',
            field=models.IntegerField(default=10),
        ),
    ]
