# Generated by Django 2.1.3 on 2018-11-22 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20181122_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='play_modal',
            new_name='play_event',
        ),
    ]
