# Generated by Django 2.1.3 on 2018-11-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20181122_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='buzz_time',
            field=models.IntegerField(default=0),
        ),
    ]
