# Generated by Django 2.1.1 on 2018-11-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_auto_20181123_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(blank=True, default='SJDV', max_length=30),
        ),
        migrations.AlterField(
            model_name='team',
            name='buzz_time',
            field=models.FloatField(default=0, unique=True),
        ),
    ]
